version: "3"
services:
  db:
    container_name: "quiz_db"
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '5432:5432'
    volumes:
      - './pg_data:/var/lib/postgresql/data'
    restart: always
    networks:
      - app-network
  back:
    build:
      context: ./
    ports:
      - '3000:3000'
    networks:
      - app-network
    volumes:
      - ./upload:/var/www/quiz/uploads

networks:
  app-network:
    driver: bridge
