version: "3"
services:
  db:
    container_name: "quiz_db"
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '5432:5432'
    volumes:
      - './pg_data:/var/lib/postgresql/data'
    restart: always

  back:
    build:
      context: ./
    ports:
      - '3000:3000'
    volumes:
      - ./uploads:/var/www/quiz_backend/uploads
      - ./resized:/var/www/quiz_backend/uploads/resized
      - ./media:/var/www/quiz_backend/media
    depends_on:
      - db
    restart: always

volumes:
  quiz_db:
